version: '3.8'

services:
  goback2onedrive:
    image: goback2onedrive:latest
    container_name: goback2onedrive-backup
    volumes:
      - /path/to/folder1:/app/data/folder1 # 要備份的資料夾，可無限增加，只需掛載到 /app/data/ 下即可
      - /path/to/folder2:/app/data/folder2
      - /path/to/store/backups:/app/backups # 備份檔的存放位置
    environment:
      - CLIENT_ID=your_client_id
      - CLIENT_SECRET=your_client_secret
      - TENANT_ID=your_tenant_id
      - DRIVE_ID=your_drive_id
      - ONEDRIVE_DESTINATION_FOLDER=goback2onedrive-backups  # OneDrive 上的目標資料夾
      - MAX_BACKUPS=5  # 要保留的最大備份數
      - BACKUP_SCHEDULE=0 2 * * *  # 設定每天凌晨 2 點備份
    restart: always

    command: >
      sh -c "
      /app/GoBack2Onedrive && \
      echo '$BACKUP_SCHEDULE /app/GoBack2Onedrive' > /etc/crontabs/root && \
      crond -f"
